Repository wecode-bootcamp-korea/31-1st-TheCreationOfWeb-frontend, pull requests merged in 2022-04, with the labels that each got.

#6 [31기 남용현] ADD: 공통 Aside 메뉴 구현
  src/components/Aside/Aside.js
  src/components/Aside/Aside.scss
  src/components/Aside/MenuList/ListItem.js
  src/components/Aside/MenuList/ListItem.scss
  src/components/Aside/MenuList/MenuList.js
  src/components/Aside/MenuList/MenuList.scss
Labels: Status: 리뷰 요청

#7 [31기 남용현] ADD: 공통 header 메뉴 구현
  src/components/Header/Header.js
  src/components/Header/Header.scss
Labels: Status: 리뷰 요청

#12 [31기 김동욱] ADD : 마이페이지 기본 레이아웃
  src/pages/MyPage/BoxData.js
  src/pages/MyPage/BoxData.scss
  src/pages/MyPage/MyPage.js
  src/pages/MyPage/MyPage.scss
Labels: Status: Accepted

#5 [31기 김동욱] ADD : 로그인 페이지 레이아웃 및 로그인 기능구현
  src/Router.js
  src/index.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#11 [31기 남용현] MODIFY : 장바구니 페이지 -> 리뷰 수정 사항 반영, sider 수정
  src/pages/Cart/BlankCart.js
  src/pages/Cart/BlankCart.scss
  src/pages/Cart/Cart.js
  src/pages/Cart/Cart.scss
  src/pages/Cart/CartItem.js
  src/pages/Cart/CartItem.scss
  src/pages/Cart/CartSummary.js
  src/pages/Cart/ValidCart.js
  src/pages/Cart/ValidCart.scss
  src/pages/Cart/cartSummary.scss
  src/pages/Cart/components/CartModal/CartModal.js
  src/pages/Cart/components/CartModal/CartModal.scss
Labels: Status: 리뷰 요청

#13 [31기 남용현] MODIFY: 공통 header 수정사항 반영 (css 수정)
  src/components/Header/Header.js
  src/components/Header/Header.scss
Labels: Status: 리뷰 요청

#10 [31기 노영완]ADD: footer구현
  package-lock.json
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: Status: 리뷰 요청

#14 [31기 남용현] MODIFY: 공통 Aside 수정사항 반영
  src/components/Aside/Aside.js
  src/components/Aside/Aside.scss
  src/components/Aside/MenuList/ListItem.js
  src/components/Aside/MenuList/ListItem.scss
  src/components/Aside/MenuList/MenuList.js
  src/styles/variables.scss
Labels: Status: 리뷰 요청

#8 [31기 남용현] MODIFY: 상품 페이지 구현, state 네이밍 수정사항 반영
  public/data/initialData.json
  src/FruitContext.js
  src/LoginContext.js
  src/Router.js
  src/index.js
  src/pages/Product/Components/Detail/Detail.js
  src/pages/Product/Components/Detail/Detail.scss
  src/pages/Product/Components/Detail/DetailBtn.js
  src/pages/Product/Components/Detail/DetailBtn.scss
  src/pages/Product/Components/Detail/DetailInfo.js
  src/pages/Product/Components/Detail/DetailInfo.scss
  src/pages/Product/Components/Detail/DetailSelect.js
  src/pages/Product/Components/Detail/DetailSelect.scss
  src/pages/Product/Components/ProductList/ProductItem.js
  src/pages/Product/Components/ProductList/ProductItem.scss
  src/pages/Product/Components/ProductList/ProductList.js
  src/pages/Product/Components/ProductList/ProductList.scss
  src/pages/Product/Products.js
Labels: Status: 리뷰 요청

#16 [31기 노영완] Direct페이지 구현
  public/images/Direct.jpg
  src/Router.js
  src/pages/Direct/Direct.js
  src/pages/Direct/Direct.scss
Labels: Status: 리뷰 요청

#18 [31기 남용현] ADD: contact 페이지 추가
  src/components/Footer/Footer.js
  src/pages/Cart/Cart.js
  src/pages/Contact/Contact.js
  src/pages/Contact/Contact.scss
Labels: Status: 리뷰 요청

#19 [31기 남용현] ADD: 로그인 유무에 따른 메뉴 타이틀 변경
  public/images/titlelogo.png
  src/components/Aside/Aside.js
  src/components/Aside/Aside.scss
  src/components/Header/Header.js
Labels: Status: 리뷰 요청

#22 [31기 김동욱]ADD: 회원가입 기능구현
  src/Router.js
Labels: Status: 리뷰 요청

#23 [31기 김동욱] ADD:mypage 기능구현
  src/pages/MyPage/BoxData.js
  src/pages/MyPage/MyPage.js
Labels: Status: 리뷰 요청

#15 [31기 김동욱] ADD: profile 기본 레이아웃 - conflict 수정
  src/Router.js
  src/pages/Profile/Profile.js
  src/pages/Profile/Profile.scss
Labels: Status: 리뷰 요청

#20 [31기 남용현] ADD: 장바구니 추가 삭제 조회 백엔드 연결 코드 추가 - 충돌 해결
  public/data/cartData.json
  src/pages/Cart/Cart.js
  src/pages/Cart/CartItem.js
  src/pages/Cart/CartItem.scss
  src/pages/Cart/CartSummary.js
  src/pages/Cart/ValidCart.js
Labels: Status: 리뷰 요청

#21 [31기 김동욱] ADD: Modify-login-text 로그인 페이지 기능구현 -conflict 수정
  public/index.html
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
Labels: Status: 리뷰 요청

#24 [31기 남용현] ADD: 상품 페이지 API 연결 기능 구현
  src/pages/Product/Components/Detail/Detail.js
  src/pages/Product/Components/Detail/DetailBtn.js
  src/pages/Product/Components/Detail/DetailInfo.js
  src/pages/Product/Components/ProductList/ProductItem.js
  src/pages/Product/Products.js
Labels: Status: 리뷰 요청

#25 [31기 남용현] MODIFY: 메뉴이동 path 수정
  src/components/Aside/MenuList/ListItem.js
  src/components/Aside/MenuList/MenuList.js
Labels: Status: 리뷰 요청

#27 [31기 남용현] MODIFY: mypage navigate 주소 변경
  src/components/Header/Header.js
Labels: Status: 리뷰 요청

#28 [31기 노영완] Direct 이미지 변경 Router 수정
  public/images/단체.jpeg
  src/Router.js
  src/pages/Direct/Direct.js
Labels: Status: 리뷰 요청

#29 [31기 남용현] MODIFY: 로그인 안됐을시 메뉴 접근 예외처리
  public/images/main.jpg
  src/Router.js
  src/components/Header/Header.js
  src/pages/Main/Main.js
Labels: Status: 리뷰 요청

#30 [31기 남용현] MODIFY: 장바구니 페이지 주소 수정
  src/Router.js
  src/config.js
  src/pages/Cart/Cart.js
  src/pages/Cart/CartItem.js
  src/pages/Cart/ValidCart.js
  src/pages/Cart/cartSummary.scss
  src/pages/Join/Join.js
  src/pages/Login/Login.js
  src/pages/Product/Components/Detail/Detail.js
  src/pages/Product/Components/Detail/Detail.scss
  src/pages/Product/Components/Detail/DetailBtn.js
  src/pages/Product/Components/ProductList/ProductItem.scss
  src/pages/Product/Products.js
Labels: Status: 리뷰 요청

#31 [31기 노영완]Modify:merge후 Slide 재 수정
  public/images/main1.jpg
  public/images/main2.jpg
  public/images/main3.jpg
  public/images/main4.jpg
  public/images/main5.jpg
  src/pages/Main/Main.js
  src/pages/Main/Main.scss
  src/pages/Main/MainSection/MainSection.scss
Labels: Status: 추가 기능 구현중
